//go:build !ignore_autogenerated

/*
 Copyright 2025, NVIDIA CORPORATION & AFFILIATES

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpectrumXRailPoolConfig) DeepCopyInto(out *SpectrumXRailPoolConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpectrumXRailPoolConfig.
func (in *SpectrumXRailPoolConfig) DeepCopy() *SpectrumXRailPoolConfig {
	if in == nil {
		return nil
	}
	out := new(SpectrumXRailPoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpectrumXRailPoolConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpectrumXRailPoolConfigList) DeepCopyInto(out *SpectrumXRailPoolConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpectrumXRailPoolConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpectrumXRailPoolConfigList.
func (in *SpectrumXRailPoolConfigList) DeepCopy() *SpectrumXRailPoolConfigList {
	if in == nil {
		return nil
	}
	out := new(SpectrumXRailPoolConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpectrumXRailPoolConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpectrumXRailPoolConfigSpec) DeepCopyInto(out *SpectrumXRailPoolConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpectrumXRailPoolConfigSpec.
func (in *SpectrumXRailPoolConfigSpec) DeepCopy() *SpectrumXRailPoolConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SpectrumXRailPoolConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpectrumXRailPoolConfigStatus) DeepCopyInto(out *SpectrumXRailPoolConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpectrumXRailPoolConfigStatus.
func (in *SpectrumXRailPoolConfigStatus) DeepCopy() *SpectrumXRailPoolConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SpectrumXRailPoolConfigStatus)
	in.DeepCopyInto(out)
	return out
}
